services:
  # 1. Base de Datos PostgreSQL
  db:
    image: postgres:15
    container_name: clinipets-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  # 2. Tu Backend Spring Boot
  app:
    image: ${BACKEND_IMAGE}
    container_name: clinipets-app
    build: . # Esto permite hacer 'docker-compose build' si tienes el Dockerfile ahí
    environment:
      SPRING_PROFILES_ACTIVE: prod
      # Conexión DB Normalizada
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      # Secretos inyectados desde .env
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      MERCADOPAGO_ACCESS_TOKEN: ${MERCADOPAGO_ACCESS_TOKEN}
      N8N_API_KEY: ${N8N_API_KEY}
      N8N_WEBHOOK_URL: ${N8N_WEBHOOK_URL}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: no
    healthcheck:
      # Usa curl para llamar al endpoint de Actuator.
      # Si devuelve 200 OK, está sano. Si falla (exit 1), está enfermo.
      test: "curl -f http://localhost:8080/actuator/health || exit 1"
      interval: 30s      # Preguntar cada 30 segundos
      timeout: 10s       # Esperar máximo 10s respuesta
      retries: 3         # Si falla 3 veces seguidas -> RESTART
      start_period: 40s  # Darle 40s de gracia al inicio para que arranque Java


  # 3. n8n (El Orquestador de Automatización)
  n8n:
    image: n8nio/n8n
    container_name: clinipets-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=washona # ¡Cámbialo al entrar!
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      # Esto es importante para los Webhooks locales
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  postgres-data:
  n8n_data: